# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kilve\PycharmProjects\QSteamKeyManager\ui\OssUsed.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_Oss_Used(object):
    def setupUi(self, Oss_Used):
        Oss_Used.setObjectName("Oss_Used")
        Oss_Used.resize(542, 254)
        self.verticalLayout = QtWidgets.QVBoxLayout(Oss_Used)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(Oss_Used)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.tableWidget = QtWidgets.QTableWidget(Oss_Used)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.layout_bottom = QtWidgets.QHBoxLayout()
        self.layout_bottom.setObjectName("layout_bottom")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_bottom.addItem(spacerItem)
        self.pushButton_close = QtWidgets.QPushButton(Oss_Used)
        self.pushButton_close.setObjectName("pushButton_close")
        self.layout_bottom.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.layout_bottom)

        self.retranslateUi(Oss_Used)
        self.pushButton_close.clicked.connect(Oss_Used.close)
        QtCore.QMetaObject.connectSlotsByName(Oss_Used)

    def retranslateUi(self, Oss_Used):
        _translate = QtCore.QCoreApplication.translate
        Oss_Used.setWindowTitle(_translate("Oss_Used", "Open-source Software Used"))
        self.label_heading.setText(_translate("Oss_Used", "The following software and libraries are used by QSKM:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Oss_Used", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Oss_Used", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Oss_Used", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Oss_Used", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Oss_Used", "Software"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Oss_Used", "Author"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Oss_Used", "License"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Oss_Used", "Python"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Oss_Used", "Python Software Foundation"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Oss_Used", "PSFL"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Oss_Used", "Qt Open Source"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Oss_Used", "The Qt Company"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Oss_Used", "(L)GPL v3"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Oss_Used", "PyQt5 and PyQt5-sip"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Oss_Used", "Riverbank Computing Limited"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Oss_Used", "GPL v3"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Oss_Used", "pyperclip"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Oss_Used", "Al Sweigart"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Oss_Used", "BSD"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_close.setText(_translate("Oss_Used", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Oss_Used = QtWidgets.QDialog()
    ui = Ui_Oss_Used()
    ui.setupUi(Oss_Used)
    Oss_Used.show()
    sys.exit(app.exec_())
