from PyQt5.QtWidgets import QDialog

from ui.AboutMe import Ui_about_me
from ui.OssUsed import Ui_Oss_Used


class AboutMe(Ui_about_me):
    """Adds triggers and other fun stuff based on the code generated by the Designer"""

    def setup_signals(self):
        """Define what would happen when user press the buttons"""
        # User clicks "OSS Used" -> show a list of wonderful open-sauce apps and libs used in this software
        self.pushButton_software.clicked.connect(self.show_oss_used)

    @staticmethod
    def show_oss_used():
        """Shows a list of open-sauce software used in this app"""
        oss_used = QDialog()
        ui = Ui_Oss_Used()
        ui.setupUi(oss_used)
        oss_used.exec()
